version: '3.8'

services:
  blog-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
    volumes:
      - ./src:/app/src  # Live code reload
      - ~/.m2:/root/.m2  # Maven cache
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - blog-network

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg-data-dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev_user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - blog-network

  redis: # Optional for session caching
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - blog-network

volumes:
  pg-data-dev:

networks:
  blog-network: