# =========================
# Spring Boot Application Configuration
# =========================
spring:
  application:
    name: blog-platform

  config:
    import: optional:file:.env.dev[.properties]
    activate-on-profile: dev

  # =========================
  # JWT Configuration (JSON Web Tokens)
  # =========================
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: ${JWT_EXPIRATION_MS}
    jwtCookieName: ${JWT_COOKIE_NAME}

  # =========================
  # Database Configuration (PostgreSQL)
  # =========================
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC  # Ensures consistency in timestamps
        format_sql: true  # Pretty-print SQL for debugging
    hibernate:
      ddl-auto: create  # Creates tables at startup (use `validate` for production)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # show-sql: true  # Uncomment to log SQL queries

  # =========================
  # OAuth2 Authentication (GitHub & Google)
  # =========================
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            scope:
              - user:email
              - read:user
          provider:
            google:
              authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
              user-name-attribute: sub

# =========================
# Server Configuration
# =========================
# Needed for AWS Elastic Beanstalk or Docker deployments
server:
  port: ${SERVER_PORT:8080}

# =========================
# Custom Application Configuration
# =========================

# Used by Spring Security's {baseUrl} expression in redirect-uri
baseUrl: ${BASE_URL}

# =========================
# Frontend Configuration
# =========================
frontend:
  url: ${FRONTEND_URL}

# =========================
# Image Hosting Configuration
# =========================
image:
  base:
    url: ${IMAGE_BASE_URL}

# =========================
# Logging Configuration
# =========================
logging:
  level:
    root: DEBUG
    org:
      springframework: DEBUG  # Uncomment to debug Spring framework logs
      security: TRACE  # Logs security events (change to INFO in production)
      hibernate:
    #        SQL: DEBUG  # Uncomment to log Hibernate SQL queries
    com:
      pen_penned:
        blog: DEBUG  # Enables debug logs for custom blog application classes